version: '3'
services:
  couchbase:
    container_name: couchbase-server
    image: webpt/couchbase-server:4.5.1
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
      - "11211:11211"
